name: Checks & Build

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  checks-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Cache pnpm lockfile
        uses: actions/cache@v5
        with:
          path: |
            node_modules/
            ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-lock-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-lock-

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version

      - uses: pnpm/action-setup@v6
        with:
          package_json_file: package.json

      - name: Configure pnpm store
        run: pnpm config set store-dir ~/.pnpm-store

      - name: Install dependencies
        run: pnpm ci

      - name: Run lint
        run: node --run lint

      - name: Run format
        run: node --run format

      - name: Run type-check
        run: node --run type-check

      - name: Run tests
        run: node --run test

      - name: Run build
        run: node --run build
